name: imagine2
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip=22.2.2
  - pytorch=2.2.2
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - pytorch-cuda=11.8
  - pytorch3d=0.7.6
  - numpy=1.24.3
  - pip:
    - open3d
    - termcolor
    - wandb
    - ftfy
    - regex
    - tqdm
    - imageio-ffmpeg
    - einops
    - Ninja
    - trimesh
    - natsort
    - absl-py
    - pyrender
    - absl-py>=0.7.0
    - gym>=0.17.3
    - pybullet>=3.0.4
    - matplotlib>=3.1.1
    - opencv-python>=4.1.2.30
    - meshcat>=0.0.18
    - scipy==1.9.0
    - scikit-image>=0.17.2